<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="federatecore" nsURI="http://federatecore/core.hla.iox" nsPrefix="iox.hla.core">
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HLAInteraction" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="HLAObject" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="JoinInteraction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hlaType" eType="#//SignalInteraction"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="federateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResignInteraction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hlaType" eType="#//SignalInteraction"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="federateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalInteraction" abstract="true" interface="true"
      eSuperTypes="#//HLAInteraction"/>
</ecore:EPackage>
