<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="littleints" nsURI="http://littleInts.edu" nsPrefix="littleints">
  <eSubpackages name="thoseInts" nsURI="http://thoseInts.edu" nsPrefix="moreInts">
    <eClassifiers xsi:type="ecore:EClass" name="Int4">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="intVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hlaType" eType="ecore:EClass federatecore.ecore#//HLAInteraction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Int5">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hlaType" eType="ecore:EClass federatecore.ecore#//HLAInteraction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Int6">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hlaType" eType="ecore:EClass federatecore.ecore#//HLAInteraction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Obj4">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hlaType" eType="ecore:EClass federatecore.ecore#//HLAObject"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="theseints" nsURI="http://theseInts.edu" nsPrefix="theseints">
    <eClassifiers xsi:type="ecore:EClass" name="Int3">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hlaType" eType="ecore:EClass federatecore.ecore#//HLAInteraction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Int2">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hlaType" eType="ecore:EClass federatecore.ecore#//HLAInteraction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Int1">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="doubVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hlaType" eType="ecore:EClass federatecore.ecore#//HLAInteraction"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
